# Generated by Django 4.0 on 2022-05-22 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(db_column='create_at', default=django.utils.timezone.now),
        ),
    ]
